#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kidletime
Version  : 5.50.0
Release  : 4
URL      : https://download.kde.org/stable/frameworks/5.50/kidletime-5.50.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.50/kidletime-5.50.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.50/kidletime-5.50.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: kidletime-lib
Requires: kidletime-license
Requires: kidletime-data
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev
BuildRequires : qtx11extras-dev

%description
# KIdleTime
Reporting of idle time of user and system
## Introduction
KIdleTime is a singleton reporting information on idle time. It is useful not
only for finding out about the current idle time of the PC, but also for getting
notified upon idle time events, such as custom timeouts, or user activity.

%package data
Summary: data components for the kidletime package.
Group: Data

%description data
data components for the kidletime package.


%package dev
Summary: dev components for the kidletime package.
Group: Development
Requires: kidletime-lib
Requires: kidletime-data
Provides: kidletime-devel

%description dev
dev components for the kidletime package.


%package lib
Summary: lib components for the kidletime package.
Group: Libraries
Requires: kidletime-data
Requires: kidletime-license

%description lib
lib components for the kidletime package.


%package license
Summary: license components for the kidletime package.
Group: Default

%description license
license components for the kidletime package.


%prep
%setup -q -n kidletime-5.50.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536422463
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1536422463
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kidletime
cp COPYING %{buildroot}/usr/share/doc/kidletime/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/kidletime/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/xdg/kidletime.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KIdleTime/KIdleTime
/usr/include/KF5/KIdleTime/kidletime.h
/usr/include/KF5/KIdleTime/kidletime_export.h
/usr/include/KF5/KIdleTime/private/abstractsystempoller.h
/usr/include/KF5/kidletime_version.h
/usr/lib64/cmake/KF5IdleTime/KF5IdleTimeConfig.cmake
/usr/lib64/cmake/KF5IdleTime/KF5IdleTimeConfigVersion.cmake
/usr/lib64/cmake/KF5IdleTime/KF5IdleTimeTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5IdleTime/KF5IdleTimeTargets.cmake
/usr/lib64/libKF5IdleTime.so
/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5IdleTime.so.5
/usr/lib64/libKF5IdleTime.so.5.50.0
/usr/lib64/qt5/plugins/kf5/org.kde.kidletime.platforms/KF5IdleTimeXcbPlugin0.so
/usr/lib64/qt5/plugins/kf5/org.kde.kidletime.platforms/KF5IdleTimeXcbPlugin1.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kidletime/COPYING
/usr/share/doc/kidletime/COPYING.LIB
